server:
  port: 8081

spring:
  mail:
    host: smtp.naver.com
    port: 587
    username:
    password:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

shop:
  frontend:
    url: https://shop.example.com

slack:
  webhook:
    url: http://localhost:8081/mock/slack

email:
  mock:
    url: http://localhost:8081/mock/email